### ISSUE TITLE
help me !

### ISSUE THREAD

**Issue by minhthien0711** [Tinubee/Latch-Vision#1]
hello !
can you help me ?
i can't found KittenLib.dll , ActUtlTypeLib.dll , ActUtlTypeLib.dll 
i using vision pro 9.7 
thanks you so much

**Comment by Tinubee** [comment]
KittenLib.dll is a self-created log window dll. You can delete it and delete all related errors. ActUtlTypeLib.dll ActUtlTypeLib.dll
is the part that interlocks with PLC.
If you are going to use only Cognex, you can delete this part and also delete related errors.

**Comment by Tinubee** [comment]
> hello ! can you help me ? i can't found KittenLib.dll , ActUtlTypeLib.dll , ActUtlTypeLib.dll i using vision pro 9.7 thanks you so much

KittenLib.dll is a self-created log window dll. You can delete it and delete all related errors. ActUtlTypeLib.dll ActUtlTypeLib.dll
is the part that interlocks with PLC.
If you are going to use only Cognex, you can delete this part and also delete related errors.

**Comment by minhthien0711** [comment]
i can't not debug 
[https://i.upanh.org/2023/06/14/196b2055b40800840.png](url)

**Comment by Tinubee** [comment]
> i can't not debug [https://i.upanh.org/2023/06/14/196b2055b40800840.png](ur

i can't open png file. can you send me a email screenshot of the error? (rlagud2005@naver.com)
